server:
  port: 8080


spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


  #redis配置
  redis:
    port: 6379
    host: localhost
    timeout: 3
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3


#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

